### ISSUE TITLE
有一个问题请教：如果sevice，dao模块中有Spring配置，Web层也有Spring配置，最后会加载几个Spring容器？而且Dao，Service的Bean会加载到哪里?

### ISSUE THREAD

**Issue by wushuangxiaoyu** [wangleeyom/ssm-demo#1]

**Comment by superleeyom** [comment]
@wushuangxiaoyu 关于这个问题，我是这样理解的：
1. 最后会加载几个 Spring 容器？
	- spring 配置文件 applicationContext.xml，spring MVC 配置文件 applicationContext-MVC.xml，这样项目中就有 2 个容器了。
	- Spring 是根容器，Spring MVC 是其子容器，绝大多数情况下，Spring 根容器中对于 Spring MVC 容器中的 Bean 是不可见的，而在SpringMVC 容器中对于 Spring 根容器中的 Bean 是可见的，也就是子容器可以看见父容器中的注册的 Bean。
2. Dao，Service 的 Bean 会加载到哪里？
	- spring 的配置文件中 `<context:component-scan base-package=“com.test" />`
	- 根据 spring 提供的参考手册，该配置的功能是扫描默认包下的所有的 `@Component` 注解，并且自动注册到容器中，同时也扫描 `@Service`，`@Respository` 注解，他们是继承自 `@Component`，所以对应的 Dao、Service 的 bean 自然是加载到 spring 的容器中啦。
	- 至于说 `@Controller` 的 Bean 加载到 哪个容器中，这个就得看你的配置方式了，他可以加载到 spring 根容器中，也可以加载到 Spring MVC 容器中。
